name: qyam
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

  ## App packages ##

  # State management
  get: ^4.6.6

  # Dart packages
  equatable: ^2.0.5
  dartz: ^0.10.1

  # Date and time
  intl: ^0.19.0

  # Remote Storage
  dio: ^5.5.0+1

  # Local Storage
  get_storage: ^2.1.1

  # Response design
  flutter_screenutil: ^5.9.3
  auto_size_text: ^3.0.0

  # Network
  connectivity_plus: ^6.0.3

  # Loading indicators
  flutter_spinkit: ^5.2.1

  # Packages for Image
  cached_network_image: ^3.3.1
  image_picker: ^1.1.2
  path_provider: ^2.1.3
  image_cropper: ^7.1.0
  flutter_svg: ^2.0.10+1
  photo_view: ^0.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0


flutter:

  uses-material-design: true

  # To add assets to your application :
  assets:
    - assets/fonts/
    - assets/icons/
    - assets/images/
    - assets/svgs/

  # To add fonts to your application :

  fonts:
    - family: Bukra
      fonts:
        - asset: assets/fonts/bukra/bukra-regular.otf
          style: normal
        - asset: assets/fonts/bukra/bukra-bold.ttf
          weight: 700
        - asset: assets/fonts/bukra/bukra-light.ttf
          weight: 300
        - asset: assets/fonts/bukra/bukra-medium.otf
          weight: 600
